drop table if exists vehicle_trip_info 
CREATE TABLE vehicle_trip_info 
(
  ID INTEGER NOT NULL IDENTITY ,
  VEHICLE_ID INTEGER DEFAULT NULL,
  TRIP_NO INTEGER DEFAULT NULL,
  TRIP_DURATION INTEGER DEFAULT NULL,
  PRIMARY KEY (ID)
);
